#############
### build ###
#############

# base image
FROM node:latest as build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@latest

# add app
COPY . /app

# generate build
RUN ng build --output-path=dist

############
### prod ###
############

# base image
FROM nginx:latest

# copy artifact build from the 'build environment'
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/

# run nginx
CMD sed -i -e 's/PORT/'"$PORT"'/g' /etc/nginx/nginx.conf && nginx -g 'daemon off;'
# CMD ["nginx", "-g", "daemon off;"]